---
title: "Untitled"
author: "Lærke Brædder"
date: "5/16/2021"
output: html_document
---

```{r 1. Loading all data}
pacman::p_load(tidyverse, ggplot2, dplyr)

# Loading the data:
df <-read.table("/Users/laerkebraedder/Desktop/Uni/Social and Cultural Dynamics/Exam project/NetLogo/final_table.csv",
                header = T,   # set columns names true
                sep = ",",    # define the separator between columns
                skip = 6,     # skip first 6 rows 
                fill = TRUE ) # add blank fields if rows have unequal lengths

# Giving the columns some nicer names:
df <- rename(df, male_percentage = mean.ingroup.male.percentage )
df <- rename(df, fightprob_gs      = mean.list.pr.fight.gs )
df <- rename(df, fightprob_mfratio = mean.list.pr.fight.mf.ratio )
df <- rename(df, fightprob_total   = mean.list.pr.fight.total )
df <- rename(df, POF   = fight.ratio )
```

```{r 1.1. 100 reps - Initial plots}
# Turning male-per
df$male_percentage <- as.factor(df$male_percentage)

# Creating a subset where we change gs_sd to factor:
sub1 <- df
sub1$gs_sd <- as.factor(sub1$gs_sd)

#plot
ggplot(sub1, aes(x = male_percentage, y = POF, color = gs_sd)) + 
  geom_smooth() + 
  facet_wrap(~ gs_mean, labeller = label_both) +
  labs(title = "The Effect of Group Size Heterogeneity on the POF_outcome",
       subtitle = "At Different Levels of Mean Ingroup Male Percentage",
       x = "Mean Male Percentage",
       y = "POF_outcome", 
       color = "Group Size SD")

# Creating a subset where we change male_percentage to factor:
sub2 <- df
sub2$male_percentage <- as.factor(sub2$male_percentage)

#plot
ggplot(sub2, aes(x = gs_sd, y = POF, color = male_percentage)) + 
  geom_smooth() + 
  facet_wrap(~ gs_mean, labeller = label_both) +
  labs(title = "The Effect of Group Size Heterogeneity on the POF_outcome",
       subtitle = "At Different Levels of Mean Ingroup Male Percentage",
       x = "Group Size SD",
       y = "POF_outcome", 
       color = "Mean Male Percentage")
```

```{r 1.2. 100 reps - elongating data to make facet_wrapped plot}
#Separating the df by the individual parameter probability types:
gs <- select(df, 
             X.run.number., 
             gs_mean, 
             gs_sd, 
             male_percentage, 
             fightprob_gs
             )
mf <- select(df, 
             X.run.number., 
             gs_mean, 
             gs_sd, 
             male_percentage, 
             fightprob_mfratio
             )
oc <- select(df,                  # oc stands for outcome
             X.run.number., 
             gs_mean, 
             gs_sd, 
             male_percentage, 
             POF
             )
# Adding columns containing the probability type:
gs$prob_type <- "POF_GroupSize"
gs$prob <- gs$fightprob_gs
gs$fightprob_gs <- NULL

mf$prob_type <- "POF_MFratio"
mf$prob <- mf$fightprob_mfratio
mf$fightprob_mfratio <- NULL

oc$prob_type <- "Outcome FightRatio"
oc$prob <- oc$POF
oc$POF <- NULL

# Binding the subsets into a longer df:
dflong <- rbind(gs, mf, oc)
```

```{r 1.3. 100 reps - making facet plot}
# New facet label names for POF Type variable
MP.labs <- c("MP:0", "MP:20", "MP:40", "MP:60", "MP:80", "MP:100")
names(MP.labs) <- c("0", "20", "40", "60", "80", "100")

# New facet label names for gs mean variable
GS.labs <- c("GSmean:5", "GSmean:10", "GSmean:15", "GSmean:20")
names(GS.labs) <- c("5", "10", "15", "20")

#plot:
ggplot(dflong, aes(x = gs_sd, y = prob, color = prob_type)) + 
  geom_smooth() + 
  labs(title = "The Effect of Group Size Heterogeneity on POF", 
       subtitle = "At Different Levels of Mean Ingroup Male Percentage and Mean Group Size",
       x = "Group Size SD",
       y = "POF",
       color = "POF Type") +
  facet_grid(male_percentage ~ gs_mean, 
             labeller = labeller(male_percentage = MP.labs, 
                                 gs_mean = GS.labs))
```


```{r 1.4. descriptive stats}
# We can see from the plots that in all combinations of mean group size and in-group male percentage, most drastic change seem to be happening between SD=5 and SD=10 (also between SD=0 and SD=5, but the mean outcome POF is always zero when SD=0, so we do not need to see that in a table).

tablesub <- subset(df, gs_sd == 5 | gs_sd == 10)



mean <- data.frame(aggregate(tablesub$POF, list(tablesub$gs_mean, tablesub$male_percentage, tablesub$gs_sd), mean))

mean <- dplyr::rename(mean, 
              mean_POF = x,
              gs_mean = Group.1,
              gs_sd = Group.3,
              male_percentage = Group.2
              )

sd <- data.frame(aggregate(tablesub$standard.deviation.list.pr.fight.total, list(tablesub$gs_mean, tablesub$male_percentage, tablesub$gs_sd), mean))

sd <- dplyr::rename(sd, 
              sd_POF = x,
              gs_mean = Group.1,
              gs_sd = Group.3,
              male_percentage = Group.2
              )
stats <- merge(mean, sd, by = c("gs_mean", "gs_sd", "male_percentage"))


ggplot (stats, aes(mean_POF, male_percentage, color = gs_mean)) + 
  geom_point() + 
  theme_classic() + 
  labs(title = "",
       subtitle = "",
       x = "Aggregated POF_outcome",
       y = "Mean Male Percentage",
       color = "Mean Group Size")

stats_small <- subset(stats, male_percentage == 20 | male_percentage == 60 | male_percentage == 100)
write_csv(stats_small, "stats.csv")
```



```{r Illustrative plot}
w <- c(0, 0.1, 0.4, 0.8, 1)
q <- c(0, 10, 40, 80, 100)
W <- data.frame(w, q)

ggplot(W, aes(x=q, y=w)) + 
  geom_line(color = "red") + 
  xlab("Male Percentage") + 
  ylab("POF_MFratio") + 
  ggtitle("Assumed Relationship Between POF_MFratio and Male Percentage") + 
  theme_classic()
```





```{r 2.1. Food-clustering - loading data}
# Loading the data:
df_food <-read.table("/Users/laerkebraedder/Desktop/Uni/Social and Cultural Dynamics/Exam project/NetLogo/Food cluster/4070_foodcluster_take1 food-availability-table.csv",
                header = T,   # set columns names true
                sep = ",",    # define the separator between columns
                skip = 6,     # skip first 6 rows 
                fill = TRUE ) # add blank fields if rows have unequal lengths

# Giving the columns some nicer names:
df_food <- rename(df_food, mean_male_percentage = mean..male.percentage..of.turtles )
df_food <- rename(df_food, mean_gs = mean..gs..of.turtles )
df_food <- rename(df_food, food_clustering = food.clustering )

df_food <- rename(df_food, POF_gs      = mean.list.pr.fight.gs )
df_food <- rename(df_food, POF_gs_SD      = standard.deviation.list.pr.fight.gs )

df_food <- rename(df_food, POF_mfratio = mean.list.pr.fight.mf.ratio )
df_food <- rename(df_food, POF_mfratio_SD      = standard.deviation.list.pr.fight.mf.ratio )

df_food <- rename(df_food, POF_total   = mean.list.pr.fight.total )
df_food <- rename(df_food, POF_total_SD      = standard.deviation.list.pr.fight.total )

df_food <- rename(df_food, POF   = fight.ratio )
df_food$POF_SD <- sd(df_food$POF)

```

```{r 2.2. Food-clustering - elongating the data}
#Separating the df by the individual parameter probability types:
gs_food <- select(df_food, 
             X.run.number., 
             mean_male_percentage,
             mean_gs, 
             food_clustering,
             POF_gs,
             POF_gs_SD
             )

mf_food <- select(df_food, 
             X.run.number., 
             mean_male_percentage,
             mean_gs, 
             food_clustering,
             POF_mfratio,
             POF_mfratio_SD
             )

oc_food <- select(df_food,                  # oc stands for outcome
             X.run.number., 
             mean_male_percentage,
             mean_gs, 
             food_clustering,
             POF,
             POF_SD
             )
# Adding columns containing the probability type:
gs_food$prob_type <- "POF_GroupSize"
gs_food$prob <- gs_food$POF_gs
gs_food$SD <- gs_food$POF_gs_SD
gs_food$POF_gs <- NULL
gs_food$POF_gs_SD <- NULL

gs_food$SD_mean[gs_food$food_clustering == "High"] <- mean(gs_food$SD[gs_food$food_clustering == "High"])
gs_food$SD_mean[gs_food$food_clustering == "Low"] <- mean(gs_food$SD[gs_food$food_clustering == "Low"])
gs_food$mean_mean[gs_food$food_clustering == "High"] <- mean(gs_food$prob[gs_food$food_clustering == "High"])
gs_food$mean_mean[gs_food$food_clustering == "Low"] <- mean(gs_food$prob[gs_food$food_clustering == "Low"])


mf_food$prob_type <- "POF_MFratio"
mf_food$prob <- mf_food$POF_mfratio
mf_food$SD <- mf_food$POF_mfratio_SD
mf_food$POF_mfratio <- NULL
mf_food$POF_mfratio_SD <- NULL

mf_food$SD_mean[mf_food$food_clustering == "High"] <- mean(mf_food$SD[mf_food$food_clustering == "High"])
mf_food$SD_mean[mf_food$food_clustering == "Low"] <- mean(mf_food$SD[mf_food$food_clustering == "Low"])
mf_food$mean_mean[mf_food$food_clustering == "High"] <- mean(mf_food$prob[mf_food$food_clustering == "High"])
mf_food$mean_mean[mf_food$food_clustering == "Low"] <- mean(mf_food$prob[mf_food$food_clustering == "Low"])


oc_food$prob_type <- "Outcome POF"
oc_food$prob <- oc_food$POF
oc_food$SD <- oc_food$POF_SD
oc_food$POF <- NULL
oc_food$POF_SD <- NULL

oc_food$SD_mean[oc_food$food_clustering == "High"] <- mean(oc_food$SD[oc_food$food_clustering == "High"])
oc_food$SD_mean[oc_food$food_clustering == "Low"] <- mean(oc_food$SD[oc_food$food_clustering == "Low"])
oc_food$mean_mean[oc_food$food_clustering == "High"] <- mean(oc_food$prob[oc_food$food_clustering == "High"])
oc_food$mean_mean[oc_food$food_clustering == "Low"] <- mean(oc_food$prob[oc_food$food_clustering == "Low"])

# Binding the subsets into a longer df:
df_food_long <- rbind(gs_food, mf_food, oc_food)
```

```{r 2.3. Food-clustering - barplots}

ggplot(df_food_long, aes(x=prob_type, y=prob, fill=food_clustering)) + 
  geom_bar(stat="summary", color="black",
           position=position_dodge()) + 
  labs(title = "POF",
       subtitle = "When Food Distribution is Homogenous and Constant Compared to Clustered and Variable",
       x = "Probability Type",
       y = "POF") + 
  theme_classic() +
  scale_fill_manual(values=c('lightpink','honeydew3'))



ggplot(df_food_long, aes(x=prob_type, y=SD, fill=food_clustering)) + 
  geom_bar(stat="summary", color="black",
           position=position_dodge()) + 
  labs(title = "eh",
       subtitle = "uh",
       x = "POF") + 
  theme_classic() +
  scale_fill_manual(values=c('lightpink','honeydew3'))
```

```{r 2.4. Food-clustering - boxplots}
ggplot(df_food_long, aes(x=prob_type, y=prob, fill=food_clustering)) + 
  geom_boxplot() + 
  theme_minimal() +
  scale_fill_manual(values=c('lightpink','honeydew3')) + 
  labs(title = "POF",
       subtitle = "When Food Distribution is Homogenous and Constant Compared to Clustered and Variable",
       x = "Probability Type",
       y = "POF")
```

```{r 2.5. Food-clustering - t-testing}
t.test(df_food$POF_gs[df_food$food_clustering == "High"], df_food$POF_gs[df_food$food_clustering == "Low"])

t.test(df_food$POF_mfratio[df_food$food_clustering == "High"], df_food$POF_mfratio[df_food$food_clustering == "Low"])

t.test(df_food$POF[df_food$food_clustering == "High"], df_food$POF[df_food$food_clustering == "Low"])
```



